grainrun/agentes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^agente/list/$', views.agente_list, name='agente_list'),
    url(r'^agente/new/$', views.agente_new, name='agente_new'),
    url(r'^agente/(?P<pk>\d+)/edit/$', views.agente_edit, name='agente_edit'),
    url(r'^agente/(?P<pk>\d+)/delete/$', views.agente_delete, name='agente_delete'),
    url(r'^agente/userprofile/edit/$', views.userprofile_edit, name='userprofile_edit'),
]

grainrun/grainrun/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth.views import logout, password_reset, password_reset_confirm


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^accounts/login/$', views.login,name='login'),
    url(r'',include('managers.urls')),
    url(r'', include('productores.urls')),
    url(r'', include('agentes.urls')),
    url(r'', include('operaciones.urls')),
    url(r'^sign-out/$', logout, {'next_page': '/accounts/login/'}, name='logout'),
]

grainrun/operaciones/urls.py
from django.conf.urls import url
from . import views
from django_filters.views import object_filter

urlpatterns = [
    url(r'^operacion/list/$', views.operacion_list, name='operacion_list'),
    url(r'^operacion/new/$', views.operacion_new, name='operacion_new'),
    url(r'^operacion/liquidacion/(?P<operacion_pk>\d+)/new/$', views.liquidacion_new, name='liquidacion_new'),
    url(r'^operacion/(?P<pk>\d+)/edit/$', views.operacion_edit, name='operacion_edit'),
    url(r'^operacion/(?P<pk>\d+)/delete/$', views.operacion_delete, name='operacion_delete'),
    url(r'^operacion/(?P<pk>\d+)/detail/$', views.operacion_detail, name='operacion_detail'),
    url(r'^operacion/liquidacion/P/(?P<pk>\d+)/edit/$', views.liquidacion_edit_a_precio, name='liquidacion_P_edit'),
    url(r'^operacion/liquidacion/F/(?P<pk>\d+)/edit/$', views.liquidacion_edit_a_fijar, name='liquidacion_F_edit'),
    url(r'^operacion/liquidacion/(?P<t>P|F)/(?P<pk>\d+)/delete/$', views.liquidacion_delete, name='liquidacion_delete'),
    url(r'^operacion/liquidacion/(?P<t>P|F)/(?P<pk>\d+)/detail/$', views.liquidacion_detail, name='liquidacion_detail'),

]

grainrun/operaciones/models.py
from abc import abstractmethod

from django.db import models
from productores.models import Productor
from agentes.models import Agente
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.db.models import Sum
from datetime import datetime, timedelta
from pytz import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import *

#Auditlog imports
from auditlog.models import AuditlogHistoryField
from auditlog.registry import auditlog
from django.db import models

ARGENTINA_TIME = timezone('America/Argentina/Buenos_Aires')


# Liquidacion estados identifier
ALARMA_PL = 2
ALARMA_PP = 3
ALARMA_PFP = 4
#Alarmas para mapear con filtros
ALARMA_CONTRATO_PRONTO_A_VENCERSE = 0 #para identicar los id de las alarmas en filters
ALARMA_CONTRATO_VENCIDO_PE = 1 #para identicar los id de las alarmas en filters
ALARMA_CONTRATO_CON_EXCEDENTE = 5 #para identicar los id de las alarmas en filters

L_FINALIZADA = 5
L_NON_ALARMA = 6
ALARMA_PE = 7
CONTRATO_FINALIZADO_PE = 8
CONTRATO_FINALIZADO_PFP = 9
CEND_AND_LIQ_IN_PROGRESS =10 # el contrato finalizo pero la liquidacion sigue en progreso
L_NON_APPROVED = 99


# Contrato status identifier
CENDED_WITH_ERRORS = 1
CENDED_WITHOUT_ERRORS = 2
CINPROGRESS_WITH_WARNING = 3
CINPROGRESS_WITHOUT_WARNING = 4
CENDSOON_WITH_PE = 5 # Contrato finaliza pronto con kilos pendiente de entrega
C_NO_APPROVED = 99

# Nuevos identificadores de estado de los contratos
CENDED_WITH_WARNING_IN_LIQ = 10 # El contrato finalizo y posee warning en las liquidaciones
CENDED_WITH_PE = 11 #El contrato finalizo con kilos pendientes de entrega
CEND_WITH_SURPLUS = 12 #El contrato finalizo con mayor cantidad de kilos entregados que los enunciados en el contrato
CINPROGRESS_WITH_WARNING_IN_LIQ = 13  #Contrato en progreso con warning en las liquidaciones
CINPROGRESS_WITH_SURPLUS = 14 #Contrato en progreso con mayor cantidad de kilos entregados que los enunciados en el contrato


# Estados Liquidacion a fijar
STATUS_LIQ_A_FIJAR_PE  = 1 # Pendiente de Entrega
STATUS_LIQ_A_FIJAR_PFP = 2 # Pendiente de Precio
STATUS_LIQ_A_FIJAR_PL  = 3 # Pendiente de Liquidación
STATUS_LIQ_A_FIJAR_PP  = 4 # Pendiente de Pago
STATUS_LIQ_A_FIJAR_PC  = 5 # Pagado a Cliente

# Estados Liquidacion a precio
STATUS_LIQ_A_PRECIO_PE = 1 #Pendiente de Entrega
STATUS_LIQ_A_PRECIO_PL = 2 #Pendiente de Liquidacion
STATUS_LIQ_A_PRECIO_PP = 3 #Pendiente de Pago
STATUS_LIQ_A_PRECIO_PC = 4 #Pagado a Cliente

class OpAlarmManager(models.Manager):

    '''
    It returns a list of contracts ids that are going to expire soon. It means,
    contracts whose expire date is within X days from today and
    they have tons whose state is "pendiente de entrega".
    '''
    def get_alarm0(self, agente):
        startdate = ARGENTINA_TIME.localize(datetime.today()).date()
        enddate = startdate + timedelta(days=agente.user.userprofile.alarma0_expire_days - 1)
        if agente.is_local_view:
            contratos = super().get_queryset().filter(agente=agente, fecha_fin__range=[startdate, enddate])
        else:
            contratos = super().get_queryset().filter(fecha_fin__range=[startdate, enddate])

        ids_contratos_warning = []
        for c in contratos:
            qs = LiquidacionAPrecio.objects.all() if c.op_tipo == 'P' else LiquidacionAFijar.objects.all()
            totalLiquidadas = (lambda x: x if x is not None else 0)(qs.filter(contrato=c.id, estado__gte=2)
                                                                    .aggregate(Sum('toneladas'))['toneladas__sum'])
            if c.toneladas > totalLiquidadas:
                ids_contratos_warning.append(c.id)
        return ids_contratos_warning

    '''
    It returns a list of contracts ids that have already expired. It means,
    contracts whose expire date is in the past and
    they have tons whose state is "pendiente de entrega".
    '''
    def get_alarm1(self, agente):
        today = ARGENTINA_TIME.localize(datetime.today()).date()
        if agente.is_local_view:
            contratos = super().get_queryset().filter(agente=agente, fecha_fin__lt = today )
        else:
            contratos = super().get_queryset().filter(fecha_fin__lt = today)

        ids_contartos_warning = []
        for c in contratos:
            qs = LiquidacionAPrecio.objects.all() if c.op_tipo == 'P' else LiquidacionAFijar.objects.all()
            totalLiquidadas = (lambda x: x if x is not None else 0)(qs.filter(contrato=c.id, estado__gte=2)
                                                                    .aggregate(Sum('toneladas'))['toneladas__sum'])
            if c.toneladas > totalLiquidadas:
                ids_contartos_warning.append(c.id)
        return ids_contartos_warning

    '''
    It returns a list of contracts ids that have liquidations for more tons
    than the given by the contract
    '''

    def get_alarmCE(self, agente):
        if agente.is_local_view:
            contratos = super().get_queryset().filter(agente=agente)
        else:
            contratos = super().get_queryset()

        ids_contartos_warning = []
        for c in contratos:
            qs = LiquidacionAPrecio.objects.all() if c.op_tipo == 'P' else LiquidacionAFijar.objects.all()
            totalLiquidadas = (lambda x: x if x is not None else 0)(qs.filter(contrato=c.id).aggregate(Sum('toneladas'))['toneladas__sum'])
            if c.toneladas < totalLiquidadas:
                ids_contartos_warning.append(c.id)
        return ids_contartos_warning

    '''
    '''
    def get_alarmPL(self, agente):
        date = ARGENTINA_TIME.localize(datetime.today()).date() - timedelta(days=agente.user.userprofile.alarma_liq_pl)
        if  agente.is_local_view:
            contratos = LiquidacionAPrecio.objects.filter(contrato__agente=agente, estado=2,
                                                       fecha_cambio_estado__lt=date).values('contrato__id')
            contratos = contratos.union(LiquidacionAFijar.objects.filter(contrato__agente=agente, estado=3,
                                                       fecha_cambio_estado__lt=date).values('contrato__id')).distinct()
        else:
            contratos = LiquidacionAPrecio.objects.filter(estado=2, fecha_cambio_estado__lt=date).values('contrato__id')
            contratos = contratos.union(LiquidacionAFijar.objects.filter(estado=3, fecha_cambio_estado__lt=date).values('contrato__id'))\
                        .distinct()

        return contratos

    '''
    '''
    def get_alarmPP(self, agente):
        date = ARGENTINA_TIME.localize(datetime.today()).date() - timedelta(days=agente.user.userprofile.alarma_liq_pp)
        if agente.is_local_view:
            contratos = LiquidacionAPrecio.objects.filter(contrato__agente=agente, estado=3,
                                                          fecha_cambio_estado__lt=date).values('contrato__id')
            contratos = contratos.union(LiquidacionAFijar.objects.filter(contrato__agente=agente, estado=4,
                                                                         fecha_cambio_estado__lt=date).values(
                'contrato__id')).distinct()
        else:
            contratos = LiquidacionAPrecio.objects.filter(estado=3, fecha_cambio_estado__lt=date).values('contrato__id')
            contratos = contratos.union(
                LiquidacionAFijar.objects.filter(estado=4, fecha_cambio_estado__lt=date).values('contrato__id')) \
                .distinct()

        return contratos


    def get_alarmPFP(self, agente):
        date = ARGENTINA_TIME.localize(datetime.today()).date() + timedelta(days=agente.user.userprofile.alarma_liqPFP)
        if agente.is_local_view:
            contratos = LiquidacionAFijar.objects.filter(contrato__agente=agente, estado=STATUS_LIQ_A_FIJAR_PFP,
                                                          contrato__fecha_fin__lt=date).values('contrato__id').distinct()
        else:
            contratos = LiquidacionAFijar.objects.filter(estado=STATUS_LIQ_A_FIJAR_PFP, contrato__fecha_fin__lt=date).values('contrato__id').distinct()

        return contratos


class Operacion(models.Model):
    A_PRECIO_OP = 'P'
    A_FIJAR_OP = 'F'
    OP_CHOICES = [('P', 'A PRECIO'), ('F', 'A FIJAR')]
    CEREAL_CHOICES = [('SJ', 'SOJA'), ('MA', 'MAIZ'), ('TR', 'TRIGO'), ('SR', 'SORGO'), ('GI', 'GIRASOL')]
    CURRENCY_CHOICES = [('USA', 'Dolar USA'), ('ARG', 'Peso ARG')]

    numeroContrato = models.CharField(max_length=20, blank=True, default='', verbose_name='#Contrato')
    productor = models.ForeignKey(Productor, on_delete=models.CASCADE, blank=False, null=False)
    agente = models.ForeignKey(Agente, on_delete=models.SET_NULL, blank=False, null=True)
    toneladas = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    fecha_inicio = models.DateField(auto_now=False, auto_now_add=False, verbose_name="Fecha de Inicio")
    fecha_fin = models.DateField(auto_now=False, auto_now_add=False, verbose_name="Fecha de Fin")
    cereal = models.CharField(max_length=2, choices=CEREAL_CHOICES, default='SJ')
    op_tipo = models.CharField(max_length=1, choices=OP_CHOICES, default='P', verbose_name="Tipo")
    moneda = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default='USA', verbose_name="Moneda")
    precio = models.DecimalField(blank=True, null=True, max_digits=15, decimal_places=6,
                                 validators=[MinValueValidator(Decimal('0.00')),
                                            MaxValueValidator(Decimal(999999999.999999))])

    objects = models.Manager() # The default manager.
    alarma = OpAlarmManager()

    aproved = models.BooleanField(default=False, verbose_name = 'Apr')
    history = AuditlogHistoryField()

    def clean(self):
        if self.fecha_inicio > self.fecha_fin:
            raise ValidationError(
                _('La fecha de fin de la operación debe ser igual o posterior a la fecha fin del contrato.'))

grainrun/operaciones/templates/operaciones/action_column_global_view.html
<button
        style="display:inline;margin:2px;"
        type="button"
        class="btn btn-default btn-sm op-show-liq"
        data-contrato-id = {{record.pk}}>

    <span style="display:inline;color:blue" class="glyphicon glyphicon-chevron-down"></span>
</button>

<button style="display:inline;margin:2px;" type="button" class="btn btn-default btn-sm"
       onclick="location.href='{% url 'operacion_edit' pk=record.pk %}';">
    <span style="display:inline;" class="glyphicon glyphicon-edit"></span>
</button>


<button style="display:inline;margin:2px;" type="button" class="btn btn-default btn-sm"
        onclick=" DeleteOperacionModal('{{ record.short_description }}','{% url 'operacion_delete' pk=record.pk  %}')">
    <span style="display:inline;" class="glyphicon glyphicon-trash"></span>
</button>

grainrun/operaciones/templates/operaciones/action_column_local_view.html
<button
        style="display:inline;margin:2px;"
        type="button"
        class="btn btn-default btn-sm op-show-liq"
        data-contrato-id = {{record.pk}}>

    <span style="display:inline;color:blue" class="glyphicon glyphicon-chevron-down"></span>
</button>

<button style="display:inline;margin:2px;" type = "button" class ="btn btn-default btn-sm"
    onclick="location.href='{% url 'operacion_detail' pk=record.pk %}';">
    <span style="display:inline;"  class ="glyphicon glyphicon-info-sign" ></span >
</button >

grainrun/operaciones/templates/operaciones/liquidacion_edit.html
{% extends 'managers/form.html' %}
{% load static %}
{% load widget_tweaks %}



{% block menu %}
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}"/>
    <link rel="stylesheet" href="{% static 'manager/css/tableStyle.css' %}">
    {% include "managers/tabs.html" with active_tab='operaciones' %}
{% endblock %}



{% block content_header %}

    <div style="margin:1%;padding:15px 0 10px 0;">
        <h2 style="display:inline;">Editar Operación</h2>
    </div>

{% endblock content_header %}


{% block submit_row %}
    <div class="submit-row">
        <input style="margin:0 0 0 8px;float:right" type="submit" value="Guardar" class="btn btn-primary"
               name="_save">
        {% if to_be_approved %}
            <input style="margin:0 0 0 8px;float:right;" type="submit" value="Guardar y Aprobar" class="btn btn-success" name="_approve">
        {% endif %}
    </div>
{% endblock submit_row %}

grainrun/operaciones/templates/operaciones/liquidacion_new.html
{% extends 'managers/form.html' %}
{% load static %}
{% load widget_tweaks %}



{% block menu %}
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}"/>
    <link rel="stylesheet" href="{% static 'manager/css/tableStyle.css' %}">
    {% include "managers/tabs.html" with active_tab='operaciones' %}
{% endblock %}

{% block content_header %}

    <div style="margin:1%;padding:15px 0 10px 0;">
        <h2 style="display:inline;">Agregar Liquidación</h2>
    </div>


{% endblock content_header %}



{% block submit_row %}
    <div class="submit-row">
        <input style="margin:0 0 0 8px;float:right" type="submit" value="Guardar" class="btn btn-primary"
               name="_save">
        <input style="margin:0 0 0 8px;float:right" type="submit" value="Guardar y agregar otro"
               class="btn btn-primary" name="_addanother">
    </div>
{% endblock submit_row %}

grainrun/operaciones/templates/operaciones/operacion_detail.html
{% extends 'managers/form.html' %}
{% load static %}
{% load widget_tweaks %}



{% block menu %}
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}"/>
    <link rel="stylesheet" href="{% static 'manager/css/tableStyle.css' %}">
    {% include "managers/tabs.html" with active_tab='operaciones' %}
{% endblock %}



{% block content_header %}

    <div style="margin:1%;padding:15px 0 10px 0;">
        <h2 style="display:inline;">Detalles</h2>
    </div>

{% endblock content_header %}

grainrun/operaciones/templates/operaciones/operacion_edit.html
{% extends 'managers/form.html' %}
{% load static %}
{% load widget_tweaks %}



{% block menu %}
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}"/>
    <link rel="stylesheet" href="{% static 'manager/css/tableStyle.css' %}">
    {% include "managers/tabs.html" with active_tab='operaciones' %}
{% endblock %}



{% block content_header %}

    <div style="margin:1%;padding:15px 0 10px 0;">
        <h2 style="display:inline;">Editar Operación</h2>
    </div>

{% endblock content_header %}


{% block submit_row %}
    <div class="submit-row">
        <input style="margin:0 0 0 8px;float:right" type="submit" value="Guardar" class="btn btn-primary"
               name="_save">
        {% if to_be_approved %}
            <input style="margin:0 0 0 8px;float:right;" type="submit" value="Guardar y Aprobar" class="btn btn-success" name="_approve">
        {% endif %}
    </div>
{% endblock submit_row %}

{% block formJQReadyFunction %}
    $('#id_op_tipo').on("change", function () {
    if ($('#id_op_tipo').val() == 'P')
    $("#id_row_precio").show();
    else
    $("#id_row_precio").hide();
    })
    $( "#id_op_tipo" ).trigger( "change" );


{% endblock formJQReadyFunction %}

grainrun/operaciones/templates/operaciones/operacion_new.html
{% extends 'managers/form.html' %}
{% load static %}
{% load widget_tweaks %}



{% block menu %}
    <link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}"/>
    <link rel="stylesheet" href="{% static 'manager/css/tableStyle.css' %}">
    {% include "managers/tabs.html" with active_tab='operaciones' %}
{% endblock %}


{% block content_header %}

    <div style="margin:1%;padding:15px 0 10px 0;">
        <h2 style="display:inline;">Agregar Operación</h2>
    </div>


{% endblock content_header %}

{% block submit_row %}
    <div class="submit-row">
        <input type="submit" value="Guardar" class="btn btn-primary"
               name="_save">
        <input type="submit" value="Guardar y agregar otro"
               class="btn btn-primary" name="_addanother">
        <input style="background-color: darkgoldenrod" type="submit" value="Guardar y agregar liquidación"
               class="btn btn-primary" name="_addLiquidacion">

    </div>
{% endblock submit_row %}



{% block formJQReadyFunction %}
    $('#id_op_tipo').on("change", function () {
    if ($('#id_op_tipo').val() == 'P')
    $("#id_row_precio").show();
    else
    $("#id_row_precio").hide();
    });
{% endblock formJQReadyFunction %}